// 원격 기관 카탈로그를 사용할 수 없을 때 쓰는 기본 기관 목록입니다.
import type { InstitutionCatalog } from "./institution-types";

const fallbackFetchedAt = "2026-06-07T00:00:00.000Z";

export const fallbackInstitutionCatalog: InstitutionCatalog = {
  version: 1,
  fetchedAt: fallbackFetchedAt,
  source: "fallback",
  institutions: [
    {
      name: "신한카드",
      institutionType: "card",
      enabled: true,
      sortOrder: 10,
      parserKey: "shinhan-card",
      homepageUrl: "https://www.shinhancard.com/",
      mobileAppUrl:
        "https://apps.apple.com/kr/app/%EC%8B%A0%ED%95%9C-sol%ED%8E%98%EC%9D%B4-%EC%8B%A0%ED%95%9C%EC%B9%B4%EB%93%9C-%EB%8C%80%ED%91%9C%ED%94%8C%EB%9E%AB%ED%8F%BC/id572462317",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["이용일자", "이용금액", "가맹점명"],
      dateColumnHints: ["이용일자", "승인일자", "거래일자"],
      amountColumnHints: ["이용금액", "승인금액", "사용금액"],
      merchantColumnHints: ["가맹점명", "이용가맹점", "사용처"],
      statusColumnHints: ["상태", "승인상태", "매입상태"],
      pcSteps: [
        "1. 신한카드 홈페이지에 로그인합니다.",
        "2. 이용내역 메뉴에서 기간을 선택합니다.",
        "3. 엑셀 또는 CSV 파일로 내려받습니다.",
      ],
      mobileSteps: [
        "1. 신한 SOL페이 앱에서 카드 이용내역을 엽니다.",
        "2. 필요한 기간을 선택한 뒤 공유 또는 저장 기능을 확인합니다.",
      ],
      notes: "국내 승인 내역 기준으로 내려받은 파일을 먼저 사용합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "현대카드",
      institutionType: "card",
      enabled: true,
      sortOrder: 20,
      parserKey: "hyundai-card",
      homepageUrl: "https://www.hyundaicard.com/",
      mobileAppUrl: "https://apps.apple.com/kr/app/%ED%98%84%EB%8C%80%EC%B9%B4%EB%93%9C/id702653088",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["이용일자", "이용금액", "가맹점명"],
      dateColumnHints: ["이용일자", "승인일자", "매출일자"],
      amountColumnHints: ["이용금액", "승인금액", "청구금액"],
      merchantColumnHints: ["가맹점명", "이용가맹점", "사용처"],
      statusColumnHints: ["상태", "승인상태", "매입상태"],
      pcSteps: [
        "1. 현대카드 홈페이지에 로그인합니다.",
        "2. 이용내역 또는 명세서 메뉴에서 기간을 선택합니다.",
        "3. 엑셀 또는 CSV 파일로 저장합니다.",
      ],
      mobileSteps: [
        "1. 현대카드 앱에서 이용내역을 엽니다.",
        "2. 기간을 선택한 뒤 내보내기 또는 공유 가능한 파일을 저장합니다.",
      ],
      notes: "할부 내역은 승인금액과 청구금액 중 실제 지출로 볼 금액을 확인합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "국민은행",
      institutionType: "bank",
      enabled: true,
      sortOrder: 30,
      parserKey: "bank-file",
      homepageUrl: "https://www.kbstar.com/",
      mobileAppUrl: "https://apps.apple.com/kr/app/kb%EC%8A%A4%ED%83%80%EB%B1%85%ED%82%B9/id373742138",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["거래일시", "출금액", "입금액", "거래내용"],
      dateColumnHints: ["거래일시", "거래일자", "일자"],
      amountColumnHints: ["출금액", "입금액", "거래금액", "금액"],
      merchantColumnHints: ["거래내용", "적요", "보낸분/받는분", "내용"],
      statusColumnHints: ["처리상태", "거래상태"],
      pcSteps: [
        "1. KB국민은행 인터넷뱅킹에 로그인합니다.",
        "2. 조회하려는 계좌의 거래내역을 엽니다.",
        "3. 기간을 선택하고 엑셀 또는 CSV 파일로 내려받습니다.",
      ],
      mobileSteps: [
        "1. KB스타뱅킹 앱에서 계좌 거래내역을 엽니다.",
        "2. 기간을 선택한 뒤 공유 또는 파일 저장 기능을 확인합니다.",
      ],
      notes: "입금액과 출금액이 분리된 파일은 두 금액 열을 함께 확인합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "하나은행",
      institutionType: "bank",
      enabled: true,
      sortOrder: 40,
      parserKey: "bank-file",
      homepageUrl: "https://www.hanabank.com/",
      mobileAppUrl:
        "https://apps.apple.com/kr/app/%ED%95%98%EB%82%98%EC%9D%80%ED%96%89-%EC%83%88%EB%A1%9C%EC%9B%8C%EC%A7%84-%ED%95%98%EB%82%98%EC%9B%90%ED%81%90%EB%A5%BC-%EA%B2%BD%ED%97%98%ED%95%B4-%EB%B3%B4%EC%84%B8%EC%9A%94/id6743190232",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["거래일시", "출금액", "입금액", "거래내용"],
      dateColumnHints: ["거래일시", "거래일자", "일자"],
      amountColumnHints: ["출금액", "입금액", "거래금액", "금액"],
      merchantColumnHints: ["거래내용", "적요", "보낸분/받는분", "내용"],
      statusColumnHints: ["처리상태", "거래상태"],
      pcSteps: [
        "1. 하나은행 인터넷뱅킹에 로그인합니다.",
        "2. 계좌 거래내역 조회 화면에서 기간을 선택합니다.",
        "3. 엑셀 또는 CSV 파일로 내려받습니다.",
      ],
      mobileSteps: [
        "1. 하나원큐 앱에서 계좌 거래내역을 엽니다.",
        "2. 기간을 선택한 뒤 공유 또는 저장 가능한 파일을 확인합니다.",
      ],
      notes: "출금 거래는 지출, 입금 거래는 수입 후보로 분류합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "토스뱅크",
      institutionType: "bank",
      enabled: true,
      sortOrder: 50,
      parserKey: "bank-file",
      homepageUrl: "https://www.tossbank.com/",
      mobileAppUrl: "https://apps.apple.com/kr/app/%ED%86%A0%EC%8A%A4/id839333328",
      supportedFormats: ["csv", "xlsx"],
      requiredColumns: ["거래일시", "거래금액", "거래내용"],
      dateColumnHints: ["거래일시", "거래일자", "일시"],
      amountColumnHints: ["거래금액", "출금액", "입금액", "금액"],
      merchantColumnHints: ["거래내용", "적요", "상대방", "내용"],
      statusColumnHints: ["처리상태", "거래상태"],
      pcSteps: [
        "1. 토스뱅크는 앱 중심 서비스이므로 PC 내려받기보다 앱 거래내역 공유를 먼저 확인합니다.",
      ],
      mobileSteps: [
        "1. 토스 앱에서 토스뱅크 계좌를 엽니다.",
        "2. 거래내역에서 필요한 기간을 선택합니다.",
        "3. 공유 또는 파일 저장 기능으로 거래내역을 내보냅니다.",
      ],
      notes: "토스 앱에서 내려받은 계좌 거래내역 파일을 기준으로 사용합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "네이버페이",
      institutionType: "pay",
      enabled: true,
      sortOrder: 60,
      parserKey: "naver-pay",
      homepageUrl: "https://pay.naver.com/",
      mobileAppUrl: "https://apps.apple.com/kr/app/%EB%84%A4%EC%9D%B4%EB%B2%84%ED%8E%98%EC%9D%B4/id1554807824",
      supportedFormats: ["csv", "tsv", "txt"],
      requiredColumns: ["날짜", "항목", "금액"],
      dateColumnHints: ["날짜", "일자", "결제일", "거래일자"],
      amountColumnHints: ["금액", "결제금액", "사용금액"],
      merchantColumnHints: ["항목", "가맹점명", "사용처", "결제처", "내용", "상품명"],
      statusColumnHints: ["유형", "구분", "상태"],
      pcSteps: [
        "1. 네이버페이에 로그인합니다.",
        "2. 결제내역 또는 Npay 머니 내역을 엽니다.",
        "3. 일괄 파일 다운로드가 보이지 않으면 날짜, 항목, 금액, 유형 열로 CSV 또는 TXT 파일을 만듭니다.",
      ],
      mobileSteps: [
        "1. 네이버페이 앱에서 결제내역 또는 머니 내역을 엽니다.",
        "2. 필요한 기간의 내역을 확인합니다.",
        "3. 공유 파일이 없으면 PC에서 CSV 또는 TXT로 정리해 업로드합니다.",
      ],
      notes: "소비자용 일괄 CSV/xls 다운로드는 공식 안내를 확인하지 못했습니다. 화면 내역을 표로 정리한 CSV/TXT를 사용합니다.",
      updatedAt: fallbackFetchedAt,
    },
  ],
};
