// 원격 기관 카탈로그를 사용할 수 없을 때 쓰는 기본 기관 목록입니다.
import type { InstitutionCatalog } from "./institution-types";

const fallbackFetchedAt = "2026-06-07T00:00:00.000Z";

export const fallbackInstitutionCatalog: InstitutionCatalog = {
  version: 1,
  fetchedAt: fallbackFetchedAt,
  source: "fallback",
  institutions: [
    {
      name: "신한카드",
      institutionType: "card",
      enabled: true,
      sortOrder: 10,
      parserKey: "shinhan-card",
      homepageUrl: "https://www.shinhancard.com/",
      mobileAppUrl: "https://www.shinhancard.com/pconts/html/mobile/mobileCard/appCard/R01/MOBFM10100R02.html",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["이용일자", "이용금액", "가맹점명"],
      dateColumnHints: ["이용일자", "승인일자", "거래일자"],
      amountColumnHints: ["이용금액", "승인금액", "사용금액"],
      merchantColumnHints: ["가맹점명", "이용가맹점", "사용처"],
      statusColumnHints: ["상태", "승인상태", "매입상태"],
      pcSteps: [
        "1. 신한카드 홈페이지에 로그인합니다.",
        "2. 이용내역 메뉴에서 기간을 선택합니다.",
        "3. 엑셀 또는 CSV 파일로 내려받습니다.",
      ],
      mobileSteps: [
        "1. 신한 SOL페이 앱에서 카드 이용내역을 엽니다.",
        "2. 필요한 기간을 선택한 뒤 공유 또는 저장 기능을 확인합니다.",
      ],
      notes: "국내 승인 내역 기준으로 내려받은 파일을 먼저 사용합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "현대카드",
      institutionType: "card",
      enabled: true,
      sortOrder: 20,
      parserKey: "hyundai-card",
      homepageUrl: "https://www.hyundaicard.com/",
      mobileAppUrl: "https://play.google.com/store/apps/details?id=com.hyundaicard.appcard",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["이용일자", "이용금액", "가맹점명"],
      dateColumnHints: ["이용일자", "승인일자", "매출일자"],
      amountColumnHints: ["이용금액", "승인금액", "청구금액"],
      merchantColumnHints: ["가맹점명", "이용가맹점", "사용처"],
      statusColumnHints: ["상태", "승인상태", "매입상태"],
      pcSteps: [
        "1. 현대카드 홈페이지에 로그인합니다.",
        "2. 이용내역 또는 명세서 메뉴에서 기간을 선택합니다.",
        "3. 엑셀 또는 CSV 파일로 저장합니다.",
      ],
      mobileSteps: [
        "1. 현대카드 앱에서 이용내역을 엽니다.",
        "2. 기간을 선택한 뒤 내보내기 또는 공유 가능한 파일을 저장합니다.",
      ],
      notes: "할부 내역은 승인금액과 청구금액 중 실제 지출로 볼 금액을 확인합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "국민은행",
      institutionType: "bank",
      enabled: true,
      sortOrder: 30,
      parserKey: "bank-file",
      homepageUrl: "https://www.kbstar.com/",
      mobileAppUrl: "https://play.google.com/store/apps/details?id=com.kbstar.kbbank",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["거래일시", "출금액", "입금액", "거래내용"],
      dateColumnHints: ["거래일시", "거래일자", "일자"],
      amountColumnHints: ["출금액", "입금액", "거래금액", "금액"],
      merchantColumnHints: ["거래내용", "적요", "보낸분/받는분", "내용"],
      statusColumnHints: ["처리상태", "거래상태"],
      pcSteps: [
        "1. KB국민은행 인터넷뱅킹에 로그인합니다.",
        "2. 조회하려는 계좌의 거래내역을 엽니다.",
        "3. 기간을 선택하고 엑셀 또는 CSV 파일로 내려받습니다.",
      ],
      mobileSteps: [
        "1. KB스타뱅킹 앱에서 계좌 거래내역을 엽니다.",
        "2. 기간을 선택한 뒤 공유 또는 파일 저장 기능을 확인합니다.",
      ],
      notes: "입금액과 출금액이 분리된 파일은 두 금액 열을 함께 확인합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "하나은행",
      institutionType: "bank",
      enabled: true,
      sortOrder: 40,
      parserKey: "bank-file",
      homepageUrl: "https://www.hanabank.com/",
      mobileAppUrl: "https://www.hanabank.com/oneQp/",
      supportedFormats: ["xls", "xlsx", "csv"],
      requiredColumns: ["거래일시", "출금액", "입금액", "거래내용"],
      dateColumnHints: ["거래일시", "거래일자", "일자"],
      amountColumnHints: ["출금액", "입금액", "거래금액", "금액"],
      merchantColumnHints: ["거래내용", "적요", "보낸분/받는분", "내용"],
      statusColumnHints: ["처리상태", "거래상태"],
      pcSteps: [
        "1. 하나은행 인터넷뱅킹에 로그인합니다.",
        "2. 계좌 거래내역 조회 화면에서 기간을 선택합니다.",
        "3. 엑셀 또는 CSV 파일로 내려받습니다.",
      ],
      mobileSteps: [
        "1. 하나원큐 앱에서 계좌 거래내역을 엽니다.",
        "2. 기간을 선택한 뒤 공유 또는 저장 가능한 파일을 확인합니다.",
      ],
      notes: "출금 거래는 지출, 입금 거래는 수입 후보로 분류합니다.",
      updatedAt: fallbackFetchedAt,
    },
    {
      name: "토스뱅크",
      institutionType: "bank",
      enabled: true,
      sortOrder: 50,
      parserKey: "bank-file",
      homepageUrl: "https://www.tossbank.com/",
      mobileAppUrl: "https://play.google.com/store/apps/details?id=viva.republica.toss",
      supportedFormats: ["csv", "xlsx"],
      requiredColumns: ["거래일시", "거래금액", "거래내용"],
      dateColumnHints: ["거래일시", "거래일자", "일시"],
      amountColumnHints: ["거래금액", "출금액", "입금액", "금액"],
      merchantColumnHints: ["거래내용", "적요", "상대방", "내용"],
      statusColumnHints: ["처리상태", "거래상태"],
      pcSteps: [
        "1. 토스뱅크는 앱 중심 서비스이므로 PC 내려받기보다 앱 거래내역 공유를 먼저 확인합니다.",
      ],
      mobileSteps: [
        "1. 토스 앱에서 토스뱅크 계좌를 엽니다.",
        "2. 거래내역에서 필요한 기간을 선택합니다.",
        "3. 공유 또는 파일 저장 기능으로 거래내역을 내보냅니다.",
      ],
      notes: "토스 앱에서 내려받은 계좌 거래내역 파일을 기준으로 사용합니다.",
      updatedAt: fallbackFetchedAt,
    },
  ],
};
